<template>
  <section>
    <b-field>
      <b-radio>Basic</b-radio>
    </b-field>
    <b-field>
      <b-radio>Basic</b-radio>
    </b-field>
    <b-field>
      <b-radio>Basic</b-radio>
    </b-field>
  </section>
</template>
